doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        use_savepoints: true
        schema_filter: ~^(?!view_benefit_month_category)~
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        schema_ignore_classes:
            - App\Entity\ViewBenefitMonth
            - App\Entity\ViewBenefitMonthCanal
            - App\Entity\ViewBenefitMonthCategory
            - App\Entity\ViewBenefitMonthClient
            - App\Entity\ViewBenefitMonthProduct
            - App\Entity\ViewBenefitYear
            - App\Entity\ViewBenefitYearCanal
            - App\Entity\ViewBenefitYearClient
            - App\Entity\ViewBenefitYearProduct
            - App\Entity\ViewBestProductSalesMonth
            - App\Entity\ViewBestProductSalesMonthCanal
            - App\Entity\ViewBestProductSalesMonthCategory
            - App\Entity\ViewBestProductSalesMonthClient
            - App\Entity\ViewBestProductSalesYear
            - App\Entity\ViewBestProductSalesYearCanal
            - App\Entity\ViewBestProductSalesYearCategory
            - App\Entity\ViewBestProductSalesYearClient
            - App\Entity\ViewCanalMonth
            - App\Entity\ViewCanalMonthCategory
            - App\Entity\ViewCanalMonthProduct
            - App\Entity\ViewCanalYearCategory
            - App\Entity\ViewCanalYearProduct
        mappings:
            App:
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"
            schema_filter: ~^(?!view_)~
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
