nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true  # CRITIQUE pour withCredentials
    paths:
        '^/api/':
            allow_origin: ['^http://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
            allow_headers: ['X-Requested-With', 'Content-Type', 'Authorization', 'X-CSRF-Token']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
            allow_credentials: true
