# config/packages/security.yaml
security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    users:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    refresh_token:
      pattern: ^/api/token/refresh
      stateless: true
      refresh_jwt:
        check_path: /api/token/refresh

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~
      custom_authenticators:
        - App\Security\JWTAuthenticator

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/logout, roles: PUBLIC_ACCESS }
    - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/test-email, roles: PUBLIC_ACCESS }
    - { path: ^/api/email-config, roles: PUBLIC_ACCESS }
    - { path: ^/api/forgot-password, roles: PUBLIC_ACCESS }
    - { path: ^/api/reset-password, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/contact-email, roles: PUBLIC_ACCESS }
    - { path: ^/api/contact-testeur, roles: PUBLIC_ACCESS }
    - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/api/docs, roles: PUBLIC_ACCESS }
    - { path: ^/stripe/webhook, roles: PUBLIC_ACCESS }
    - { path: ^/api/subscriptions/success, roles: PUBLIC_ACCESS }
    - { path: ^/api/subscriptions/cancel, roles: PUBLIC_ACCESS }
    - { path: ^/api/subscriptions, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
    ROLE_PRO: [ROLE_USER]
    ROLE_UNLIMITED: [ROLE_PRO, ROLE_USER]

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
