parameters:
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.publishable_key: '%env(STRIPE_PUBLISHABLE_KEY)%'
    stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'
            $stripeWebhookSecret: '%stripe.webhook_secret%'

    # Configuration pour les param√®tres publiques
    app.stripe_config:
        class: stdClass
        public: true
        properties:
            publishable_key: '%stripe.publishable_key%'